### ISSUE TITLE
Set active organization is broken in 1.3.2 and future versions

### ISSUE THREAD

**Issue by iRoachie** [better-auth/better-auth#3589]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

Create a next js project and create an auth instance with the organization plugin.

Create an organization
Create a user
Add user to the organization

After logging in, attempt to set the active organization using authClient

```ts
await authClient.organization.setActive({
  organizationSlug: selectedOrganization,
});
```

### Current vs. Expected behavior

The expected behaviour is that the organization specified should be set active.

The current behaviour is that /api/auth/organization/set-active returns 403

### What version of Better Auth are you using?

1.3.2

### Provide environment information

```bash
- Mac 15.5 (24F74)
- Edge 138.0.3351.95
```

### Which area(s) are affected? (Select all that apply)

Backend, Client

### Auth config (if applicable)

```typescript

```

### Additional context

Works in 1.3.1

**Comment by iRoachie** [comment]
The user is a member. The list of organizations was returned using `authClient.organization.listInvitations`

The response from the `organization.setActive` is

```json
{
    "code": "USER_IS_NOT_A_MEMBER_OF_THE_ORGANIZATION",
    "message": "User is not a member of the organization",
    "status": 403,
    "statusText": "FORBIDDEN"
}
```

**Comment by iRoachie** [comment]
I added some logs to the drizzleAdapter, and I found the issue. 

The new code added in #3497 does not work when `organizationSlug` is used, only id.

```
2025-07-24T16:44:54.701Z INFO [Better Auth]: [Drizzle Adapter] #14 [1/3] findOne: {
  model: 'members',
  where: [
    {
      operator: 'eq',
      connector: 'AND',
      field: 'userId',
      value: 'FnbgGyhPnGjqNf0NNDnINUotPTmTQtUx'
    },
    {
      operator: 'eq',
      connector: 'AND',
      field: 'organizationId',
      value: 'FxnpLdiVJjq3TrtuhSWiWvg9MKZPF9EU'
    }
  ],
  select: undefined
}
```

Check attempts to use `organizationId` even when `organizationSlug` is passed in

**Comment by Soluce-Technologies** [comment]
> I added some logs to the drizzleAdapter, and I found the issue.
> 
> The new code added in [#3497](https://github.com/better-auth/better-auth/pull/3497) does not work when `organizationSlug` is used, only id.
> 
> ```
> 2025-07-24T16:44:54.701Z INFO [Better Auth]: [Drizzle Adapter] #14 [1/3] findOne: {
>   model: 'members',
>   where: [
>     {
>       operator: 'eq',
>       connector: 'AND',
>       field: 'userId',
>       value: 'FnbgGyhPnGjqNf0NNDnINUotPTmTQtUx'
>     },
>     {
>       operator: 'eq',
>       connector: 'AND',
>       field: 'organizationId',
>       value: 'FxnpLdiVJjq3TrtuhSWiWvg9MKZPF9EU'
>     }
>   ],
>   select: undefined
> }
> ```
> 
> Check attempts to use `organizationId` even when `organizationSlug` is passed in

Same error on my side, better auth try to compare with organization id when using the slug.
