### ISSUE TITLE
Cannot use better-auth cli to generate schema

### ISSUE THREAD

**Issue by l0seq** [better-auth/better-auth#3951]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

1. Run `bunx --bun @better-auth/cli generate --config src/auth/index.ts`
2. CLI will return: `Cannot find module 'zod/v4' from '/tmp/bunx-1000-@better-auth/cli@latest/node_modules/@better-auth/cli/dist/index.mjs'`

### Current vs. Expected behavior

Migrations should be generated normally as expected, but this error is returned.

### What version of Better Auth are you using?

1.3.5

### System info

```bash
System:
    OS: Linux 6.12 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 18.50 GB / 30.21 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chromium: 138.0.7204.157
```

### Which area(s) are affected? (Select all that apply)

Other

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "../database";
import { account, appInvitation, session, user, verification } from "../database/schema";
import { admin } from "better-auth/plugins";
import { appInvite } from "@better-auth-kit/app-invite"

export const auth = betterAuth({
    database: drizzleAdapter(db, {
        provider: "sqlite",
        schema: {
            user,
            account,
            session,
            verification,
            appInvitation
        },
    }),
    emailAndPassword: {
        enabled: true,
        disableSignUp: false,
    },
    plugins: [
        admin(),
        appInvite({
            sendInvitationEmail: async (data) => {
                /*  WIP */
            },
            allowUserToCreateInvitation: (user) => {
                return true;
                /*  WIP */
            }
        })
    ]
});
```

### Additional context

I have tested it with npx and bunx, same behavior

**Comment by Kinfe123** [comment]
can you provide me a repro for this issue. this should have been resolved by the previous PR.

**Comment by hannesfant** [comment]
I believe this might be isolated to Bun, I'm having the same issue in a fresh terminal (& project) with bunx, while npx seems to work. The downside is that we're using Bun's sql driver, so the script is still failing on a bun:sql import, though it's at least running without any zod import errors

**Comment by l0seq** [comment]
> can you provide me a repro for this issue. this should have been resolved by the previous PR.

I can't @Kinfe123, the problem just happens when i launch the command, no particular behavior



> I believe this might be isolated to Bun, I'm having the same issue in a fresh terminal (& project) with bunx, while npx seems to work. The downside is that we're using Bun's sql driver, so the script is still failing on a bun:sql import, though it's at least running without any zod import errors

@hannesfant you are right, i have retried with npm and i have this error:

`2025-08-12T16:55:36.046Z ERROR [Better Auth]: Couldn't read your auth config. Error: Cannot find module 'bun:sqlite'`

UPDATE: when i try with better-auth cli 1.3.4 with this command:

`bunx --bun @better-auth/cli@1.3.4 generate --config src/auth/index.ts`

It works without any problem, so i think it's a problem with 1.3.5

**Comment by dmythro** [comment]
> UPDATE: when i try with better-auth cli 1.3.4 with this command:
> 
> `bunx --bun @better-auth/cli@1.3.4 generate --config src/auth/index.ts`
> 
> It works without any problem, so i think it's a problem with 1.3.5

Thanks for mentioning `cli 1.3.4`, saved a lot of time for me now!

**Comment by timothyallan** [comment]
I'm also getting this on node with `"better-auth": "^1.3.6",` FWIW
```
npx @better-auth/cli migrate

Need to install the following packages:
@better-auth/cli@1.3.6
Ok to proceed? (y) y

node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'zod' imported from /Users/ta/.npm/_npx/167ca1f116d365e6/node_modules/@better-auth/cli/dist/index.mjs
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:96:40)
    at link (node:internal/modules/esm/module_job:95:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.17.0
```

**Comment by Kinfe123** [comment]
@timothyallan  can you try updating your node version ?

**Comment by timothyallan** [comment]
Sure, updated to the latest LTS version with same result with 1.3.6, 1.3.4 works well.

```
npx @better-auth/cli migrate       
node:internal/modules/package_json_reader:255
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'zod' imported from /Users/ta/.npm/_npx/167ca1f116d365e6/node_modules/@better-auth/cli/dist/index.mjs
    at Object.getPackageJSONURL (node:internal/modules/package_json_reader:255:9)
    at packageResolve (node:internal/modules/esm/resolve:767:81)
    at moduleResolve (node:internal/modules/esm/resolve:853:18)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:783:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:707:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:690:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:307:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:183:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v22.18.0

npx @better-auth/cli@1.3.4 migrate                                                                                                                                          
⠋ preparing migration...[2025-08-13T23:16:18.853Z] [warn] ....
```

**Comment by Kinfe123** [comment]
i cant seems to reproduce it. can you please do a minimal repro for this if possible. since your issue is also different from the author itself.

**Comment by Rhayxz** [comment]
> i cant seems to reproduce it. can you please ship a minimal repro for this if possible. since your issue is also different from the author itself.

Got the same issue, and fix was to revert to 1.3.4 and under. As you can see below, it works with 1.3.4 and down, but errors on 1.3.5 and above:

```
Running with v1.2.12:

root@Computer:/home/me/projects/proj-1/apps/api# bunx @better-auth/cli@1.2.12 generate --config src/auth/better-auth.config.ts --output src/db/auth.schema.ts -y
2025-08-14T19:50:57.966Z SUCCESS [Better Auth]: 🚀 Schema was overwritten successfully!

---
Running with v1.3.4:
root@Computer:/home/me/projects/proj-1/apps/api# bunx @better-auth/cli@1.3.4 generate --config src/auth/better-auth.config.ts --output src/db/auth.schema.ts -y
✔ The file src/db/auth.schema.ts already exists. Do you want to overwrite the schema to the file? … yes
2025-08-14T19:51:02.561Z SUCCESS [Better Auth]: 🚀 Schema was overwritten successfully!

---
Running with v1.3.5:
root@Computer:/home/me/projects/proj-1/apps/api# bunx @better-auth/cli@1.3.5 generate --config src/auth/better-auth.config.ts --output src/db/auth.schema.ts -y
node:internal/modules/esm/resolve:274
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/bunx-0-@better-auth/cli@1.3.5/node_modules/zod/dist/esm/v4/index.js' imported from /tmp/bunx-0-@better-auth/cli@1.3.5/node_modules/@better-auth/cli/dist/index.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:799:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:723:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:706:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:307:38)
    at #link (node:internal/modules/esm/module_job:163:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///tmp/bunx-0-@better-auth/cli@1.3.5/node_modules/zod/dist/esm/v4/index.js'
}

Node.js v24.0.2

---
Running with v1.3.6:
root@Computer:/home/me/projects/proj-1/apps/api# bunx @better-auth/cli@1.3.6 generate --config src/auth/better-auth.config.ts --output src/db/auth.schema.ts -y
node:internal/modules/esm/resolve:274
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/bunx-0-@better-auth/cli@1.3.6/node_modules/zod/dist/esm/v4/index.js' imported from /tmp/bunx-0-@better-auth/cli@1.3.6/node_modules/@better-auth/cli/dist/index.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:799:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:723:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:706:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:307:38)
    at #link (node:internal/modules/esm/module_job:163:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///tmp/bunx-0-@better-auth/cli@1.3.6/node_modules/zod/dist/esm/v4/index.js'
}

Node.js v24.0.2
```

**Comment by Kinfe123** [comment]
Have you installed zod ? and what version is this ?. it is currently peerDep.

**Comment by elartix** [comment]
hi, @Bekacru 

```@better-auth/cli@1.3.7
Ok to proceed? (y) y

node:internal/modules/esm/resolve:873
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'zod' imported from C:\Users\MYUSER\AppData\Local\npm-cache\_npx\05eee8cc65087e98\node_modules\@better-auth\cli\dist\index.mjs
    at packageResolve (node:internal/modules/esm/resolve:873:9)
    at moduleResolve (node:internal/modules/esm/resolve:946:18)
    at defaultResolve (node:internal/modules/esm/resolve:1188:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:642:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:591:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:574:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:236:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:130:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

Zod not installed in npx cache folder `\AppData\Local\npm-cache\_npx\05eee8cc65087e98\node_modules\`

<img width="427" height="565" alt="Image" src="https://github.com/user-attachments/assets/b92289a6-e496-4d56-961e-5b5f189dff3d" />

# Workaround

1. install `@better-auth/cli` as global package (will be installed with zod) 
2. Create custom scripts and add into node folder, (in my case `C:\Users\MYUSER\AppData\Roaming\nvm\v20.19.3`)

**better-auth**
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/node_modules/@better-auth/cli/dist/index.mjs" "$@"
else 
  exec node  "$basedir/node_modules/@better-auth/cli/dist/index.mjs" "$@"
fi
```

**better-auth.cmd**
```
@ECHO off
GOTO start
:find_dp0
SET dp0=%~dp0
EXIT /b
:start
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%"  "%dp0%\node_modules\@better-auth\cli\dist\index.mjs" %*
```

**better-auth.ps1**
```
#!/usr/bin/env pwsh
$basedir=Split-Path $MyInvocation.MyCommand.Definition -Parent

$exe=""
if ($PSVersionTable.PSVersion -lt "6.0" -or $IsWindows) {
  # Fix case when both the Windows and Linux builds of Node
  # are installed in the same directory
  $exe=".exe"
}
$ret=0
if (Test-Path "$basedir/node$exe") {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "$basedir/node$exe"  "$basedir/node_modules/@better-auth/cli/dist/index.mjs" $args
  } else {
    & "$basedir/node$exe"  "$basedir/node_modules/@better-auth/cli/dist/index.mjs" $args
  }
  $ret=$LASTEXITCODE
} else {
  # Support pipeline input
  if ($MyInvocation.ExpectingInput) {
    $input | & "node$exe"  "$basedir/node_modules/@better-auth/cli/dist/index.mjs" $args
  } else {
    & "node$exe"  "$basedir/node_modules/@better-auth/cli/dist/index.mjs" $args
  }
  $ret=$LASTEXITCODE
}
exit $ret
```

Run:
```
better-auth generate ...
```

[better-auth.cmd.txt](https://github.com/user-attachments/files/21824250/better-auth.cmd.txt)
[better-auth.ps1.txt](https://github.com/user-attachments/files/21824252/better-auth.ps1.txt)
[better-auth.txt](https://github.com/user-attachments/files/21824251/better-auth.txt)

I guess will be fixed soon

**Comment by Kinfe123** [comment]
It is peerDep right now. We don't bundle zod with the cli. You should install the version you want to avoid version mismatch but we have mention the range version on peerDep value. Please can you try installing and see if the issue persists

**Comment by Kinfe123** [comment]
Or give me a reproducible if installing your zod version does not work ?

**Comment by bunday** [comment]
I can confirm using `better-auth/cli@1.3.4` solves the problem for now

**Comment by himself65** [comment]
> Have you installed zod ? and what version is this ?. it is currently peerDep.

In some case, pnpm won't install peerDepp afai, not sure if this is related

**Comment by himself65** [comment]
maybe related https://github.com/oven-sh/bun/issues/16970

**Comment by nicognaW** [comment]
i had the same issue with bunx before. checked my bunx dir and found zod at 3.25.0. and i saw here

https://github.com/better-auth/better-auth/blob/d921471a742109c8c5c930b8c7aadcf4c40c9ca0/packages/cli/package.json#L67

that @better-auth/cli's peer dep requires "zod": "3.25.0 || ^4.0.0".

guessing bun installed the first match 3.25.0, but my project uses v4, causing the error. installing @better-auth/cli as dev dep in the project works. likely due to bun pm vs npm differences

**Comment by Pirulax** [comment]
I've managed to fix this by installing latest node (not sure if it's a must), and adding `zod` to my dev deps: `yarn add -D zod`. Now it works.

**Comment by strblr** [comment]
Same issue, `better-auth/cli@1.3.4` worked but only with node 23. Node 24 made it fail as well but with a completely different error (node-gyp related).

**Comment by himself65** [comment]
> Same issue, `better-auth/cli@1.3.4` worked but only with node 23. Node 24 made it fail as well but with a completely different error (node-gyp related).

node-gyp seems not to be related to better-auth since we don't have that in our code and our deps.

Can you show the error log? Thanks

**Comment by strblr** [comment]
@himself65 Sure. It happens with better-auth/cli@1.3.4 and Node 24.6.0:

```
> bun run db:auth:generate
$ bunx @better-auth/cli@1.3.4 generate --config server/utils/auth.ts --output server/db/auth.schema.ts
  ⚙️  @prisma/client [4/4] 
make: Entering directory '/tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3/build'
  TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
make: Leaving directory '/tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3/build'

(node:734875) [DEP0176] DeprecationWarning: fs.R_OK is deprecated, use fs.constants.R_OK instead
(Use `node --trace-deprecation ...` to show where the warning was created)
prebuild-install warn install No prebuilt binaries found (target=24.6.0 runtime=node arch=x64 libc= platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@11.4.1
gyp info using node@24.6.0 | linux | x64
gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args '/tmp/bunx-1000-node-gyp@latest/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/tmp/bunx-1000-node-gyp@latest/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/user/.cache/node-gyp/24.6.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/user/.cache/node-gyp/24.6.0',
gyp info spawn args '-Dnode_gyp_dir=/tmp/bunx-1000-node-gyp@latest/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/user/.cache/node-gyp/24.6.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 32 ]
make: cc: No such file or directory
make: *** [deps/sqlite3.target.mk:200: Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/tmp/bunx-1000-node-gyp@latest/node_modules/node-gyp/lib/build.js:219:23)
gyp ERR! System Linux 5.15.167.4-microsoft-standard-WSL2
gyp ERR! command "/home/user/.nvm/versions/node/v24.6.0/bin/node" "/tmp/bunx-1000-node-gyp@latest/node_modules/.bin/node-gyp" "rebuild" "--release"
gyp ERR! cwd /tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3
gyp ERR! node -v v24.6.0
gyp ERR! node-gyp -v v11.4.1
gyp ERR! not ok 

error: install script from "better-sqlite3" exited with 1
error: script "db:auth:generate" exited with code 1
```

**Comment by himself65** [comment]
> No such file or directory

https://github.com/WiseLibs/better-sqlite3/issues/1326
https://github.com/WiseLibs/better-sqlite3/issues/1330

It is definitely caused by `better-sqlite3`. I would recommend you clean up the cache and node_modules and try installing again.

**Comment by strblr** [comment]
Good catch, thanks! I'll try that later

**Comment by louiejakebell** [comment]
I was experiencing the same issue related to not being able to find the `zod` module and took a quick look through the comments here

For me the fix was
- Using Node `v20.19.0` (I don't think this part is necessarily relevant but adding it as details anyhow)
- Adding `zod` as a dependency (I do not actually use it in application but temporarily added it for running the script once)
- Using specifically version `1.3.4` of the CLI as mentioned above (can be achieved directly via `npx @better-auth/cli@1.3.4 migrate`)

**Comment by depsimon** [comment]
> Have you installed zod ? and what version is this ?. it is currently peerDep.

Shouldn't it be a devDependency as it breaks the CLI when used with npx/bunx?

I'm not using zod in my project, and I don't want to install it alongside another validation lib

**Comment by himself65** [comment]
Thanks for the feedback. We got it fixed in the Canary version. Will release stable soon!

**Comment by krisnaw** [comment]
hi @himself65 Any info on when the fix for this bug will be released?

**Comment by Bicheka** [comment]
I was having this issue today where it would be impossible to generate the schema when running `bun x @better-auth/cli@latest generate` I would get this error:
```
[#better-auth]: Couldn't read your auth config. Error: Cannot find module 'bun'
Require stack:
- /home/bicheka/projects/tudoo/services/auth/node_modules/drizzle-orm/bun-sql/driver.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1421:15)
    at require.resolve (node:internal/modules/helpers:163:19)
    at jitiResolve (/tmp/bunx-1000-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:148703)
    at jitiRequire (/tmp/bunx-1000-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:150290)
    at import (/tmp/bunx-1000-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:158307)
    at /home/bicheka/projects/tudoo/services/auth/node_modules/drizzle-orm/bun-sql/driver.js:1:247
    at eval_evalModule (/tmp/bunx-1000-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:155533)
    at /tmp/bunx-1000-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:154214
    at async import (/tmp/bunx-1000-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:158301)
    at async /home/bicheka/projects/tudoo/services/auth/node_modules/drizzle-orm/bun-sql/index.js:1:186 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/bicheka/projects/tudoo/services/auth/node_modules/drizzle-orm/bun-sql/driver.js'
  ]
}
``` 

**I was able to generate the schema after many trials with this command:**
`bunx --bun @better-auth/cli@1.3.4 generate --config ./src/lib/auth.ts`

If I change the version or if I remove the --bun or if I remove the --config ./src/lib/auth.ts it stops working.

**Comment by strblr** [comment]
> [@himself65](https://github.com/himself65) Sure. It happens with better-auth/cli@1.3.4 and Node 24.6.0:
> 
> ```
> > bun run db:auth:generate
> $ bunx @better-auth/cli generate --config server/utils/auth.ts --output server/db/auth.schema.ts
>   ⚙️  @prisma/client [4/4] 
> make: Entering directory '/tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3/build'
>   TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
>   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
>   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
>   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
> rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
> make: Leaving directory '/tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3/build'
> 
> (node:734875) [DEP0176] DeprecationWarning: fs.R_OK is deprecated, use fs.constants.R_OK instead
> (Use `node --trace-deprecation ...` to show where the warning was created)
> prebuild-install warn install No prebuilt binaries found (target=24.6.0 runtime=node arch=x64 libc= platform=linux)
> gyp info it worked if it ends with ok
> gyp info using node-gyp@11.4.1
> gyp info using node@24.6.0 | linux | x64
> gyp info find Python using Python version 3.12.3 found at "/usr/bin/python3"
> gyp info spawn /usr/bin/python3
> gyp info spawn args [
> gyp info spawn args '/tmp/bunx-1000-node-gyp@latest/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args 'binding.gyp',
> gyp info spawn args '-f',
> gyp info spawn args 'make',
> gyp info spawn args '-I',
> gyp info spawn args '/tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3/build/config.gypi',
> gyp info spawn args '-I',
> gyp info spawn args '/tmp/bunx-1000-node-gyp@latest/node_modules/node-gyp/addon.gypi',
> gyp info spawn args '-I',
> gyp info spawn args '/home/user/.cache/node-gyp/24.6.0/include/node/common.gypi',
> gyp info spawn args '-Dlibrary=shared_library',
> gyp info spawn args '-Dvisibility=default',
> gyp info spawn args '-Dnode_root_dir=/home/user/.cache/node-gyp/24.6.0',
> gyp info spawn args '-Dnode_gyp_dir=/tmp/bunx-1000-node-gyp@latest/node_modules/node-gyp',
> gyp info spawn args '-Dnode_lib_file=/home/user/.cache/node-gyp/24.6.0/<(target_arch)/node.lib',
> gyp info spawn args '-Dmodule_root_dir=/tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3',
> gyp info spawn args '-Dnode_engine=v8',
> gyp info spawn args '--depth=.',
> gyp info spawn args '--no-parallel',
> gyp info spawn args '--generator-output',
> gyp info spawn args 'build',
> gyp info spawn args '-Goutput_dir=.'
> gyp info spawn args ]
> gyp info spawn make
> gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 32 ]
> make: cc: No such file or directory
> make: *** [deps/sqlite3.target.mk:200: Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o] Error 127
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack at ChildProcess.<anonymous> (/tmp/bunx-1000-node-gyp@latest/node_modules/node-gyp/lib/build.js:219:23)
> gyp ERR! System Linux 5.15.167.4-microsoft-standard-WSL2
> gyp ERR! command "/home/user/.nvm/versions/node/v24.6.0/bin/node" "/tmp/bunx-1000-node-gyp@latest/node_modules/.bin/node-gyp" "rebuild" "--release"
> gyp ERR! cwd /tmp/bunx-1000-@better-auth/cli@1.3.4/node_modules/better-sqlite3
> gyp ERR! node -v v24.6.0
> gyp ERR! node-gyp -v v11.4.1
> gyp ERR! not ok 
> 
> error: install script from "better-sqlite3" exited with 1
> error: script "db:auth:generate" exited with code 1
> ```

For anyone encountering this, fixed it with:

```
sudo apt update && sudo apt install -y build-essential
```
