### ISSUE TITLE
Better-Auth 1.4.9 breaks type checks

### ISSUE THREAD

**Issue by JE4GLE** [better-auth/better-auth#6965]
### To Reproduce

1. Write the following code in version 1.4.8

  ```typescript
  const { error } = await authClient.organization.setActive({
		organizationId,
		organizationSlug
  });
  ```
2. Run any typescript checker like `svelte-kit sync && svelte-check --tsconfig ./tsconfig.json` → **everything fine**
3. Update to version 1.4.9
4. Run type checking again → **lots of errors**

The cache has been cleared and `.svelte-kit` and `node_modules` directories have been deleted

#### Current

Lots of type errors

#### Expected

No type errors

### What version of Better Auth are you using?

1.4.9 (works in 1.4.8)

### System info

```bash
The command npx @better-auth/cli info --json produces no output and results in exit code 1.
```

### Which area(s) are affected? (Select all that apply)

Types, Client

### Auth config (if applicable)

```typescript
export const authClient = createAuthClient({
	plugins: [
		adminClient(),
		passkeyClient(),
		twoFactorClient(),
		emailOTPClient(),
		magicLinkClient(),
		anonymousClient(),
		...(PUBLIC_API_KEYS === 'true' ? [apiKeyClient()] : []),
		...(PUBLIC_ORGANIZATIONS === 'true' ? [organizationClient()] : []),
		...(PUBLIC_MULTISESSION === 'true' ? [multiSessionClient()] : []),
		...(PUBLIC_STRIPE === 'true'
			? [
					stripeClient({
						subscription: PUBLIC_SUBSCRIPTIONS === 'true'
					})
				]
			: [])
	]
});
```

#### **Examples** of the type errors

I get the errors for `authClient.organization`:

```bash
Error: Property 'setActive' does not exist on type '{ checkRolePermission: <R extends "admin" | "member" | "owner">(data: ({ permission: { readonly organization?: ("update" | "delete")[] | undefined; readonly member?: ("update" | "create" | "delete")[] | undefined; readonly invitation?: ("cancel" | "create")[] | undefined; readonly team?: ("update" | ... 1 more ... |...'. 
): Promise<boolean> {
        const { error } = await authClient.organization.setActive({
                organizationId,
```

`authClient.twoFactor` (which is stating that the whole twoFactor plugin doesn't exist):

```bash
Error: Property 'twoFactor' does not exist on type '{ useListPasskeys: () => AuthQueryAtom<Passkey[]>; } & { useActiveOrganization: () => AuthQueryAtom<Prettify<{ id: string; name: string; slug: string; createdAt: Date; logo?: string | null | undefined; metadata?: any; } & { ...; }>>; useListOrganizations: () => AuthQueryAtom<...>; useActiveMember: () => AuthQueryAto...'. (ts)
        function handleVerifyCode() {
                authClient.twoFactor
                        .verifyTotp({
```

`authClient.magicLink`:

```bash
Error: Property 'magicLink' does not exist on type '{ social: <FetchOptions extends ClientFetchOption<Partial<{ provider: (string & {}) | "github" | "apple" | "atlassian" | "cognito" | "discord" | "facebook" | "figma" | "microsoft" | "google" | "huggingface" | "slack" | ... 21 more ... | "vercel"; ... 8 more ...; additionalData?: Record<...> | undefined; }> & Record<...'. (ts)
                        authClient.signIn
                                .magicLink({
                                        email: $formData.username,
```

`authClient.admin`:

```bash
Error: Property 'listUsers' does not exist on type '{ checkRolePermission: <R extends "user" | "admin">(data: ({ permission: { readonly user?: ("update" | "set-role" | "create" | "get" | "delete" | "list" | "ban" | "impersonate" | "set-password")[] | undefined; readonly session?: ("delete" | ... 1 more ... | "revoke")[] | undefined; }; permissions?: undefined; } | { ...'. (ts)
                authClient.admin
                        .listUsers({
                                query: {
``` 

and `authClient.multiSession`:

```bash
Error: Property 'multiSession' does not exist on type '{ useListPasskeys: () => AuthQueryAtom<Passkey[]>; } & { useActiveOrganization: () => AuthQueryAtom<Prettify<{ id: string; name: string; slug: string; createdAt: Date; logo?: string | null | undefined; metadata?: any; } & { ...; }>>; useListOrganizations: () => AuthQueryAtom<...>; useActiveMember: () => AuthQueryAto...'. (ts)
                }
                await authClient.multiSession.setActive({
                        sessionToken: session.token
```

**Comment by bytaesu** [comment]
Hi @JE4GLE,

Is there a reason you're assigning plugin clients dynamically? For example, if you're using Organization plugin and then set the environment variable to false, the app build would fail.

**Comment by bytaesu** [comment]
Also, this type issue isn't caused by v1.4.9 I guess.. it occurs even on v1.4.6
However, basically I don't think this is a problem with the Better Auth package 🤔

**Comment by JE4GLE** [comment]
@bytaesu Thank you for your answer. I'm currently building a project where I'm testing different features and want to disable some.

Well, I installed 1.4.8, ran svelte-check without any problems. I installed 1.4.9 without changing anything else and the validation failed.

**Comment by bytaesu** [comment]
Hi @JE4GLE,

I think it would be better to include all necessary plugins in the instance and handle branching at runtime.

**Comment by JE4GLE** [comment]
@bytaesu Thank you, I will change that
@dosu Some worked, but I were not able to find for example the type for the Admin plugin

**Comment by bytaesu** [comment]
Hello @JE4GLE,

Due to type issues caused by recent changes in the `multi-session` plugin, we reverted it a few hours ago. It seems this isn't reflected in the released v1.4.9 yet.

In the same setup as yours, the issue has been resolved in this beta version!
Please let me know if you have any questions 🙂

```
 "better-auth": "1.4.10-beta.1",
```

+) But... I still don't recommend dynamically adding or removing plugins, as it can cause issues in the app itself. Helper plugins like OpenAPI seems fine, but I think that plugins that affect runtime aren't suitable for this!

**Comment by bytaesu** [comment]
Since this issue has been resolved, I'm closing this. If you have any questions, feel free to mention me 🤗
