### ISSUE TITLE
@better-auth/passkey@1.6.12 can't be used to sign in

### ISSUE THREAD

**Issue by SourceR85** [better-auth/better-auth#9819]
### Is this suited for github?

- [x] Yes, this is suited for github

### Reproduction

Using @better-auth/passkey@1.6.12 for passkey-only login (login-flow without username/email and password):
```
const { error: responseError } = await authClient.signIn.passkey({
  fetchOptions: {
    onError(context) {  /* … logging and inform user */ },
    onSuccess() {
      // … redirect to homepage
      goto("/", { replaceState: true });
    }
  },
});
// …handle abort (not catched by onError)
```

`passkey/verify-authentication` responds with code `CHALLENGE_NOT_FOUND`
I see the verification in DB with correct `ecpectedChallenge` and request has a matching challenge in response.clientDataJSON

### Current vs. Expected behavior

Just Restore previous behaviour (worked in 1.6.11)

### What version of Better Auth are you using?

1.6.12

### System info

```bash
{
  "system": {
    "platform": "linux",
    "arch": "x64",
    "version": "#1 SMP PREEMPT_DYNAMIC Wed May 27 13:57:41 UTC 2026",
    "release": "7.0.10-201.fc44.x86_64",
    "cpuCount": 8,
    "cpuModel": "AMD Ryzen 9 9950X3D 16-Core Processor",
    "totalMemory": "60.43 GB",
    "freeMemory": "47.87 GB"
  },
  "node": {
    "version": "v26.2.0",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "11.13.0"
  },
  "frameworks": [
    {
      "name": "svelte",
      "version": "5.56.0"
    },
    {
      "name": "@sveltejs/kit",
      "version": "2.61.1"
    }
  ],
  "databases": null,
  "betterAuth": {
    "version": "Unknown",
    "config": null,
    "error": "Cannot find module '$app/environment'\nRequire stack:\n- /home/sl/Projekte/suite/src/lib/server/logger.ts"
  }
}
```

### Which area(s) are affected? (Select all that apply)

Client

### Auth config (if applicable)

```typescript
Client:

import { betterAuthLocalizationClientPlugin as localizationClientPlugin } from "better-auth-localization"
import { createAuthClient } from "better-auth/svelte"
import {
	inferAdditionalFields,
} from "better-auth/client/plugins"
import { passkeyClient } from "@better-auth/passkey/client"
import type { auth } from "./server/auth"

export const authClient = createAuthClient({
	basePath: "/auth",
	plugins: [
		localizationClientPlugin(),
		passkeyClient(),
		inferAdditionalFields<typeof auth>(),
	]
})


Server:

import { passkey } from "@better-auth/passkey"
import type { UserWithRole } from "better-auth/plugins"
import type { BetterAuthOptions } from "better-auth"

export const auth = (opts: {
	baseURL: URL,
	appName: string,
	userFromSignedContext(ctx: any, context: string): Promise<UserWithRole>
}) => ({
	...opts,
	baseURL: baseURL.origin,
	user: {
		changeEmail: {
			enabled: true,
		}
	},
	account: {
		encryptOAuthTokens: true,
	},
	advanced: {
		trustedProxyHeaders: true,
		useSecureCookies: true,
	},
	emailAndPassword: {
		enabled: false,
	},
	plugins: [
		passkey({
			authenticatorSelection: {
				residentKey: "required",
				userVerification: "preferred",
			},
			rpID: opts.baseURL.hostname,
			rpName: opts.appName,

			registration: {
				requireSession: false,
				async resolveUser({ ctx, context }) {
					if (!context) throw ctx.error("UNAUTHORIZED")

					const user = await opts.userFromSignedContext(ctx, context)
					if (!user) throw ctx.error("UNAUTHORIZED")

					return {
						id: user.id,
						name: user.email,
						displayName: user.name,
					}
				},
				async afterVerification({ ctx, verification, context }) {
					if (!verification.verified) return
					if (!context) throw ctx.error("UNAUTHORIZED")

					const user = await opts.userFromSignedContext(ctx, context)
					if (!user) throw ctx.error("UNAUTHORIZED")

					return { userId: user.id }
				}
			}
		})
	]
} satisfies BetterAuthOptions
})
```

**Comment by SourceR85** [comment]
@dosu
- `/passkey/verify-authentication` was requested with `Cookie` `better-auth.better-auth-passkey`.
- Proxy doesn't matter: error still exists in dev-server on localhost.
- Between response of `/passkey/generate-authenticate-options` till request to `/passkey/verify-authentication` was less then 5 seconds (wasn't expired).
- Error triggers on first call to `/passkey/verify-authentication`.

**Comment by SourceR85** [comment]
@dosu
- I don't have a `secondaryStorage`
- I'm using `admin` and `organization` plugins from `better-auth/plugins`
- I've derived a custom CouchDB adapter from official MongoDB adapter (they're both document database server with rest-api)

**Comment by SourceR85** [comment]
@dosu
you start hallucinating: there is no `consumeOne` in better-auth [documentation for creating database adapters](https://better-auth.com/docs/guides/create-a-db-adapter)

**Comment by bytaesu** [comment]
Hi @SourceR85,

What is the return type of `deleteMany` in your custom adapter?

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/02e8d779-8769-4e7d-9f5f-7f829e130976" />

**Comment by SourceR85** [comment]
Hi @bytaesu

I think I've fixed the bug in my custom CouchDB adapter.
it was an implementation detail:
I've expected the `id` to always have a prefix (`partition` in CouchDB terminology), but I've never implemented it for "in" and "not_in" operators…
'cause I've never searched for an array of id's (until now)

**Comment by SourceR85** [comment]
Yep, tested and fixed it.
