### PR TITLE
feat(cli): support Cloudflare Workers virtual module imports

### LINKED ISSUE #5178: generate cli doesnt work with cloudflare:workers
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

```ts
// database.ts

import { env } from "cloudflare:workers";
import type { DrizzleD1Database } from "drizzle-orm/d1";
import { drizzle } from "drizzle-orm/d1";
import * as schema from "./schema";

export type Database = DrizzleD1Database<typeof schema>;

export const db: Database = drizzle(env.DB, { schema });
```

### Current vs. Expected behavior

error log:

```
$ bunx @better-auth/cli@latest generate --config ../../apps/website/app/lib/auth.server.ts --output ./schema.ts -y
2025-10-09T02:13:19.454Z ERROR [Better Auth]: Couldn't read your auth config. Error: Cannot find module 'cloudflare:workers'
Require stack:
- /myappdir/packages/db/index.ts
    at Function._resolveFilename (node:internal/modules/cjs/loader:1244:15)
    at Function.resolve (node:internal/modules/helpers:146:19)
    at jitiResolve (/private/tmp/bunx-501-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:148703)
    at jitiRequire (/private/tmp/bunx-501-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:150290)
    at import (/private/tmp/bunx-501-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:158307)
    at /myappdir/packages/db/index.ts:1:223
    at eval_evalModule (/private/tmp/bunx-501-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:155533)
    at jitiRequire (/private/tmp/bunx-501-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:150967)
    at import (/private/tmp/bunx-501-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:158307)
    at /myappdir/apps/website/app/lib/auth.server.ts:3:25
    at async Function.import (/private/tmp/bunx-501-@better-auth/cli@latest/node_modules/jiti/dist/jiti.cjs:1:158301)
    at async resolveConfig (file:///private/tmp/bunx-501-@better-auth/cli@latest/node_modules/c12/dist/shared/c12.Bzgyhsy6.mjs:382:18)
    at async loadConfig (file:///private/tmp/bunx-501-@better-auth/cli@latest/node_modules/c12/dist/shared/c12.Bzgyhsy6.mjs:169:23)
    at async getConfig (file:///private/tmp/bunx-501-@better-auth/cli@latest/node_modules/@better-auth/cli/dist/index.mjs:1969:26)
    at async Command.generateAction (file:///private/tmp/bunx-501-@better-auth/cli@latest/node_modules/@better-auth/cli/dist/index.mjs:2705:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/myappdir/packages/db/index.ts'
  ]
}
error: script "generate-better-auth-config" exited with code 1
```

### What version of Better Auth are you using?

1.3.27

### System info

```bash
same error with this CLI


bunx @better-auth/cli info       
2025-10-09T02:15:14.663Z ERROR [Better Auth]: [#better-auth]: Couldn't read your auth config. Error: Cannot find module 'cloudflare:workers'
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "my-monorepo-package-db";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "sqlite", // or "pg" or "mysql"
  }),
  //... the rest of your config
});
```

### Additional context

monorepo dir tree

```
root
- packages
- - db
- apps
- - website
```

### PR DESCRIPTION
**Pull request by chhoumann**
This fixes #5178, which broke the CLI for anyone using Better Auth with Cloudflare Workers and D1.

## The Problem

When users run `@better-auth/cli generate` (or any CLI command) in a Cloudflare Workers project, the CLI crashes with `Cannot find module 'cloudflare:workers'`. This happens because their auth config or database setup imports Cloudflare's runtime-only virtual modules like `cloudflare:workers` or `cloudflare:test`, and when the CLI tries to load the config through JITI, Node's module resolver can't find them.

For Cloudflare D1 users, this completely blocks schema generation and migrations—they can't use the CLI at all.

## The Fix

I added a lightweight stub module that exports the key Cloudflare Workers APIs (`env`, `WorkerEntrypoint`, `DurableObject`, `RpcTarget`, etc.) as forgiving proxies. When the CLI loads a config, it now automatically resolves `cloudflare:workers` and `cloudflare:test` to this stub through JITI's alias system, just like we already do for SvelteKit's virtual modules.

The stub uses data URIs (no temp files), requires no new dependencies, and matches Cloudflare's actual API signatures closely enough that configs load without issue. The proxies absorb property access and method calls gracefully, so even if a config references `env.DB` or constructs a `DurableObject`, everything works.

## Testing

I verified this two ways:

**1. Unit tests**  
Added a regression test in `packages/cli/test/get-config.test.ts` that reproduces the exact failure from #5178—a config that imports `{ env }` from `cloudflare:workers` and uses it in the auth config. All 17 tests pass:

```bash
pnpm --filter @better-auth/cli exec vitest run test/get-config.test.ts
✓ test/get-config.test.ts (17 tests) 199ms
```

**2. Real project**  
I tested against a local Cloudflare D1 project that was failing before. First, with the published version:

```bash
❯ bun install @better-auth/cli
installed @better-auth/cli@1.3.30

❯ bunx @better-auth/cli generate --output src/db/auth-schema1.ts
ERROR: Cannot find module 'cloudflare:workers'
```

Then I linked the patched version:

```bash
❯ bun link @better-auth/cli
installed @better-auth/cli@link:@better-auth/cli

❯ bunx @better-auth/cli generate --output src/db/auth-schema1.ts
✔ Do you want to generate the schema to src/db/auth-schema1.ts? … yes
SUCCESS: 🚀 Schema was generated successfully!
```

The fix works exactly as intended.

Closes #5178.

---
## Summary by cubic
Fix the CLI crash in Cloudflare Workers projects by resolving Cloudflare virtual modules to a stub during config loading. Unblocks D1 schema generation and migrations (fixes #5178).

- **Bug Fixes**
  - Added a stub module for cloudflare:workers and cloudflare:test (env, WorkerEntrypoint, DurableObject, RpcTarget) using data URI proxies.
  - Aliased these modules in get-config via JITI so configs load without Node resolving errors.
  - Added a regression test to verify configs importing env from cloudflare:workers load correctly.

### CODE REVIEW

**Comment by xkema** [comment]
Hi! 👋 @chhoumann @Bekacru

I have a couple of updates regarding the changes made here — first of all, thanks a lot!

I've tested the changes using the `1.4.0-beta.15` tag, but I'm still experiencing the issues I described below:

1. Stubbing works like a charm; however when using it with the [aidenwallis/kysely-d1](https://github.com/aidenwallis/kysely-d1) dialect, [this line](https://github.com/aidenwallis/kysely-d1/blob/36349028c96dbc8b8995289add81fb24a9c6e4d8/src/index.ts#L106) leads to the error flow due to the truthy evaluation of the stubbing's return value. (in this case, `typeof results.error === 'function'`).
2. Even if the stubbing issue above were resolved, using a stub in the migration generation flow, also skips the DB introspection step [here](https://github.com/better-auth/better-auth/blob/67aa5a112511518e8c3ad3128befc4bdb2f6ad75/packages/better-auth/src/db/get-migration.ts#L160). I'm not sure about the full implications, but it will most likely cause confusion when creating or altering existing tables, since it has no knowledge of the current database schema due to the stubbed behavior.

These are the two issues I'm still experiencing. They seem to come from Cloudflare Workers' security sandbox limitations rather than anything specific to Better Auth. ~~Unless we have an actual emulator that can replicate the D1 Database environment outside of Cloudflare's runtime, I don't think we'll have a permanent fix for them.~~ It turns out that this information is not correct. There is actually a helper for this documented at https://developers.cloudflare.com/workers/wrangler/api/#getplatformproxy, but Better Auth also fails to resolve it, showing the error message below::

```bash
ERROR [Better Auth]: Couldn't read your auth config. TypeError: Cannot read properties of undefined (reading 'resolve')
```

I'd be more than happy to see any kind of fixes since I've already deployed shit load of code on Cloudflare Workers environment using D1 without considering authentication. 😂 

Best!

_Sorry if this isn’t the right spot for this comment! I hadn't seen it before the merge._
