### ISSUE TITLE
`apiKey.list()` TypeScript types don't match runtime response in v1.5.0-beta.10

### ISSUE THREAD

**Issue by turisanapo** [better-auth/better-auth#7695]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

1. Install `better-auth@1.5.0-beta.10`
2. Create an auth client with the apiKey plugin:

```js
import { createAuthClient } from "better-auth/client";
import { apiKeyClient } from "better-auth/client/plugins";

const authClient = createAuthClient({
  baseURL: "...",
  plugins: [apiKeyClient()],
});
```
3. Call `apiKey.list()`:

```js
const { data, error } = await authClient.apiKey.list();
data.map((key) => key.id); // TypeError: data.map is not a function
```

4. TypeScript shows `data` as an array type, but at runtime it's `{ apiKeys: [...] }`

### Current vs. Expected behavior

**Expected:** `authClient.apiKey.list()` returns `data` as an array that can be directly mapped:

```js
const { data } = await authClient.apiKey.list();
data.map((key) => key.id); // works - data is ApiKey[]
```

**Actual**: data is returned as an object with an apiKeys property, causing `TypeError: data.map is not a function`:

```js
const { data } = await authClient.apiKey.list();
// data is { apiKeys: ApiKey[] }, not ApiKey[]
data.apiKeys.map((key) => key.id); // workaround needed
```

### What version of Better Auth are you using?

v1.5.0-beta.10

### System info

```bash
{
  "system": {
    "platform": "darwin",
    "arch": "arm64",
    "version": "Darwin Kernel Version 25.1.0: Mon Oct 20 19:32:56 PDT 2025; root:xnu-12377.41.6~2/RELEASE_ARM64_T8132",
    "release": "25.1.0",
    "cpuCount": 10,
    "cpuModel": "Apple M4",
    "totalMemory": "16.00 GB",
    "freeMemory": "0.14 GB"
  },
  "node": {
    "version": "v24.9.0",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "11.6.0"
  },
  "frameworks": null,
  "databases": null,
  "betterAuth": {
    "version": "Unknown",
    "config": null
  }
}
```

### Which area(s) are affected? (Select all that apply)

Client

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth"
export const auth = betterAuth({
  emailAndPassword: {  
    enabled: true
  },
});
```

**Comment by bytaesu** [comment]
Hi @turisanapo, I'm looking into this

**Comment by bytaesu** [comment]
Hi @turisanapo,

There was an intentional breaking change introduced in https://github.com/better-auth/better-auth/pull/7424 to support pagination.

It is applied in `v1.5-beta`, and `data.apiKeys.map()` is now the new usage 🙂

**Comment by turisanapo** [comment]
@bytaesu Thanks for the clarification! After restarting my TypeScript server, the types are now correct. The issue was on my end. Apologies for the noise. Feel free to close this.

**Comment by bytaesu** [comment]
No worries @turisanapo, glad to hear the issue has been resolved 😄
