### ISSUE TITLE
[Bug] auth generate error in sveltekit app

### ISSUE THREAD

**Issue by bennajah** [better-auth/better-auth#8933]
### Is this suited for github?

- [x] Yes, this is suited for github

### Reproduction

1. clone this repo https://github.com/bennajah/svelte-better-auth
2. run auth generate
3. see the error

### Current vs. Expected behavior

getting this error
```zsh
bennajah@MacBook-Pro my-app % bun auth:schema     
$ auth generate --config src/lib/server/auth.ts --output src/lib/server/db/auth.schema.ts --yes
Couldn't read your auth config. Error: Cannot find module '/Users/bennajah/Development/projects/src/lib/server/db'
Require stack:
- /Users/bennajah/Development/projects/my-app/src/lib/server/auth.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
    at require.resolve (node:internal/modules/helpers:163:19)
    at jitiResolve (/Users/bennajah/Development/projects/my-app/node_modules/jiti/dist/jiti.cjs:1:148703)
    at jitiRequire (/Users/bennajah/Development/projects/my-app/node_modules/jiti/dist/jiti.cjs:1:150290)
    at import (/Users/bennajah/Development/projects/my-app/node_modules/jiti/dist/jiti.cjs:1:158307)
    at /Users/bennajah/Development/projects/my-app/src/lib/server/auth.ts:6:17
    at async Function.import (/Users/bennajah/Development/projects/my-app/node_modules/jiti/dist/jiti.cjs:1:158301)
    at async resolveConfig (file:///Users/bennajah/Development/projects/my-app/node_modules/c12/dist/index.mjs:318:20)
    at async loadConfig (file:///Users/bennajah/Development/projects/my-app/node_modules/c12/dist/index.mjs:147:22)
    at async getConfig (file:///Users/bennajah/Development/projects/my-app/node_modules/auth/dist/index.mjs:1591:23) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/bennajah/Development/projects/my-app/src/lib/server/auth.ts'
  ]
}
error: script "auth:schema" exited with code 1
```

### What version of Better Auth are you using?

1.5.6

### System info

```bash
{
  "system": {
    "platform": "darwin",
    "arch": "arm64",
    "version": "Darwin Kernel Version 25.4.0: Thu Mar 19 19:33:43 PDT 2026; root:xnu-12377.101.15~1/RELEASE_ARM64_T8142",
    "release": "25.4.0",
    "cpuCount": 10,
    "cpuModel": "Apple M5",
    "totalMemory": "16.00 GB",
    "freeMemory": "0.27 GB"
  },
  "node": {
    "version": "v24.14.1",
    "env": "development"
  },
  "packageManager": {
    "name": "npm",
    "version": "11.12.1"
  },
  "frameworks": [
    {
      "name": "svelte",
      "version": "^5.55.1"
    },
    {
      "name": "@sveltejs/kit",
      "version": "^2.55.0"
    }
  ],
  "databases": [
    {
      "name": "@libsql/client",
      "version": "^0.17.2"
    },
    {
      "name": "drizzle",
      "version": "^0.45.2"
    }
  ],
  "betterAuth": {
    "version": "Unknown",
    "config": null,
    "error": "Cannot find module '/Users/bennajah/Development/projects/src/lib/server/db'\nRequire stack:\n- /Users/bennajah/Development/projects/my-app/src/lib/server/auth.ts"
  }
}
```

### Which area(s) are affected? (Select all that apply)

Package

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth/minimal";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { sveltekitCookies } from "better-auth/svelte-kit";
import { env } from "$env/dynamic/private";
import { getRequestEvent } from "$app/server";
import { db } from "$lib/server/db";
import * as schema from "$lib/server/db/schema";

export const auth = betterAuth({
  baseURL: env.ORIGIN,
  secret: env.BETTER_AUTH_SECRET,
  database: drizzleAdapter(db, { provider: "sqlite", schema }),
  emailAndPassword: { enabled: true },
  plugins: [sveltekitCookies(getRequestEvent)],
});
```

**Comment by bennajah** [comment]
is working when using 
```ts
import { db } from "./db";
import * as schema from "./db/schema";
```

but this not working
```ts
import { db } from "$lib/server/db";
import * as schema from "$lib/server/db/schema";
```

**Comment by bennajah** [comment]
It works with `auth@1.5.4` when running:
```zsh
npx auth@1.5.4 generate --config src/lib/server/auth.ts --output src/lib/server/db/auth.schema.ts --yes
```
and using:
```ts
import { db } from "$lib/server/db";
import * as schema from "$lib/server/db/schema";
```

However, it throws an error when using the latest version:
```zsh
npx auth@latest generate --config src/lib/server/auth.ts --output src/lib/server/db/auth.schema.ts --yes
```

**Comment by DarthGigi** [comment]
Having the same issue, I commented here: https://github.com/better-auth/better-auth/issues/6373#issuecomment-4056158210 but I haven't gotten any replies.

```
~/Projects/MC-ID/website
pnx auth@latest generate --adapter drizzle                                                                                                                                                                                                     
[#better-auth]: Couldn't read your auth config. Error: Cannot find module '/Users/gigi/Projects/MC-ID/src/lib/server/email-service'
Require stack:
- /Users/gigi/Projects/MC-ID/website/src/lib/server/auth.ts
    at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
    at require.resolve (node:internal/modules/helpers:163:19)
    at jitiResolve (/Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:148703)
    at jitiRequire (/Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:150290)
    at import (/Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:158307)
    at /Users/gigi/Projects/MC-ID/website/src/lib/server/auth.ts:5:27
    at async Function.import (/Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:158301)
    at async resolveConfig (file:///Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/c12@3.3.4/node_modules/c12/dist/index.mjs:318:20)
    at async loadConfig (file:///Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/c12@3.3.4/node_modules/c12/dist/index.mjs:147:22)
    at async getConfig (file:///Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/auth@1.5.6_@better-fetch+fetch@1.1.21_@opentelemetry+api@1.9.1_better-call@1.3.2_zod@4._51ff88b236c456853f5a87b683b46691/node_modules/auth/dist/index.mjs:1605:23) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/gigi/Projects/MC-ID/website/src/lib/server/auth.ts' ]
}
```

I don't get why it tries to look in `/Users/gigi/Projects/MC-ID` and not `/Users/gigi/Projects/MC-ID/website` as this is a monorepo.

**Comment by bennajah** [comment]
> Having the same issue, I commented here: [#6373 (comment)](https://github.com/better-auth/better-auth/issues/6373#issuecomment-4056158210) but I haven't gotten any replies.
> 
> ```
> ~/Projects/MC-ID/website
> pnx auth@latest generate --adapter drizzle                                                                                                                                                                                                     
> [#better-auth]: Couldn't read your auth config. Error: Cannot find module '/Users/gigi/Projects/MC-ID/src/lib/server/email-service'
> Require stack:
> - /Users/gigi/Projects/MC-ID/website/src/lib/server/auth.ts
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1456:15)
>     at require.resolve (node:internal/modules/helpers:163:19)
>     at jitiResolve (/Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:148703)
>     at jitiRequire (/Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:150290)
>     at import (/Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:158307)
>     at /Users/gigi/Projects/MC-ID/website/src/lib/server/auth.ts:5:27
>     at async Function.import (/Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/jiti@2.6.1/node_modules/jiti/dist/jiti.cjs:1:158301)
>     at async resolveConfig (file:///Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/c12@3.3.4/node_modules/c12/dist/index.mjs:318:20)
>     at async loadConfig (file:///Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/c12@3.3.4/node_modules/c12/dist/index.mjs:147:22)
>     at async getConfig (file:///Users/gigi/Library/Caches/pnpm/dlx/c4ca24f8ecaec5e725d44d89afcc74114905512d4d6ead6a3d17adc8e510c4ea/19d5e488108-e9fc/node_modules/.pnpm/auth@1.5.6_@better-fetch+fetch@1.1.21_@opentelemetry+api@1.9.1_better-call@1.3.2_zod@4._51ff88b236c456853f5a87b683b46691/node_modules/auth/dist/index.mjs:1605:23) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/Users/gigi/Projects/MC-ID/website/src/lib/server/auth.ts' ]
> }
> ```
> 
> I don't get why it tries to look in `/Users/gigi/Projects/MC-ID` and not `/Users/gigi/Projects/MC-ID/website` as this is a monorepo.

you can downgrade to this cli version
auth@1.5.4

**Comment by DarthGigi** [comment]
I tried downgrading but that didn't work for me, unfortunately

**Comment by bennajah** [comment]
> I tried downgrading but that didn't work for me, unfortunately

see this

https://github.com/better-auth/better-auth/issues/8933#issuecomment-4183949759

**Comment by bytaesu** [comment]
Hi everyone 😁

```
npx https://pkg.pr.new/auth@895d48a
```

This CLI includes the fix from PR #9032, could you check if the issue is resolved with this version?

I'd like to check whether this fix resolves the issue in your setup 🙏

**Comment by DarthGigi** [comment]
@bytaesu I'm still getting the following errors:
```
[#better-auth]: Couldn't read your auth config. Error: Cannot find module '$app/environment'
[#better-auth]: Couldn't read your auth config. Error: Cannot find module '$src/app.css?inline'
```

**Comment by bytaesu** [comment]
> [@bytaesu](https://github.com/bytaesu) I'm still getting the following errors:
> 
> ```
> [#better-auth]: Couldn't read your auth config. Error: Cannot find module '$app/environment'
> [#better-auth]: Couldn't read your auth config. Error: Cannot find module '$src/app.css?inline'
> ```

I'll try to address this in a separate PR. I'll mention you once I've opened it 🫡
